
local Group = require("colorbuddy").Group
local  colors= require("colorbuddy").colors

  Group.new('Normal', colors.noir_4, colors.nb_background)
  Group.new('Search', colors.noir_9, colors.noir_0)
  Group.new('IncSearch', colors.noir_9, colors.noir_0)
  Group.new('Visual', nil, colors.noir_8)
  Group.new('SignColumn', nil, colors.nb_background)
  Group.new('LineNr', colors.noir_8, colors.nb_background)
  Group.new("EndOfBuffer", colors.noir_8, nil)

  Group.new('Comment', colors.noir_7)
  Group.new('Constant', colors.primary)
  Group.new('Character', colors.noir_5)
  Group.new('Identifier', colors.noir_0)
  Group.new('Statement', colors.noir_1)
  Group.new('PreProc', colors.primary)
  Group.new('Type', colors.secondary)
  Group.new('Special', colors.noir_5)
  Group.new('Error', colors.primary)
  Group.new('Todo', colors.primary, colors.noir_8)
  Group.new('Function', colors.noir_0)
Group.new('ColorColumn', nil, colors.noir_8)
  Group.new('Conceal', colors.noir_7)
  Group.new('Cursor', nil)
  Group.new('CursorColumn', nil, colors.noir_9)
  Group.new('CursorLine', nil, colors.noir_9)
  Group.new('CursorLineNr', colors.noir_6, colors.noir_9)
  Group.new('Directory', colors.noir_3)
  Group.new('DiffAdd', colors.primary, colors.noir_8)
  Group.new('DiffChange', colors.noir_0, colors.noir_8)
  Group.new('DiffDelete', colors.secondary, colors.noir_8)
  Group.new('DiffText', colors.noir_0, colors.noir_7)
  Group.new('ErrorMsg', colors.noir_1, colors.primary)
  Group.new('VertSplit', colors.noir_8, colors.noir_9)

  Group.new('Folded', colors.noir_5, colors.noir_8)
  Group.new('FoldColumn', colors.noir_5, colors.noir_8)
  Group.new('MatchParen', nil, colors.noir_7)
  Group.new('MoreMsg', nil, colors.noir_6)
  Group.new('NonText', colors.noir_8, nil)
  Group.new('Pmenu', colors.noir_2, colors.noir_8)
  Group.new('PmenuSel', colors.noir_6, colors.noir_8)
  Group.new('PmenuSbar', colors.primary, colors.noir_8)
  Group.new('PmenuThumb', colors.primary, colors.noir_7)
  Group.new('Question', colors.noir_1, colors.noir_8)
  Group.new('SpecialKey', colors.noir_6, nil)
  Group.new('SpellBad', colors.primary)
  Group.new('SpellCap', colors.noir_0)
  Group.new('SpellLocal', colors.noir_5)
  Group.new('SpellRare', colors.primary)
  Group.new('StatusLine', colors.noir_5, colors.noir_8)
  Group.new('TabLine', colors.noir_3, colors.noir_8)
  Group.new('TabLineFill', nil, colors.noir_8)
  Group.new('TabLineSel', colors.noir_2, nil)
  Group.new('Title', colors.noir_3)
  Group.new('VisualNOS', colors.primary, colors.noir_8)
  Group.new('WarningMsg', colors.primary)
  Group.new('WildMenu', colors.noir_5, colors.noir_8)

  Group.new('FloatBorder', colors.noir_0)
  Group.new('FloatTitle', colors.noir_0)
  Group.new('NormalFloat', colors.noir_4)


  -- Treesitter Syntax Highlighting
  -- See :help treesitter-highlight-groups
  Group.new('@boolean', colors.primary)
  Group.new('@character', colors.secondary)
  Group.new('@character.special', colors.noir_2)
  Group.new('@comment', colors.noir_7)
  Group.new('@conditional', colors.noir_2)
  Group.new('@constant', colors.mfed_dim)
  Group.new('@constant.builtin', colors.noir_2)
  Group.new('@constant.macro', colors.primary)
  Group.new('@constructor', colors.noir_1)
  Group.new('@debug', colors.noir_2)
  Group.new('@define', colors.noir_2)
  Group.new('@exception', colors.noir_2)
  Group.new('@field', colors.noir_2)
  Group.new('@float', colors.noir_2)
  Group.new('@function', colors.noir_0)
  Group.new('@function.builtin', colors.noir_2)
  Group.new('@function.call', colors.noir_2)
  Group.new('@function.macro', colors.primary)
  Group.new('@include', colors.noir_6)
  Group.new('@keyword', colors.noir_5)
  Group.new('@keyword.function', colors.noir_5)
  Group.new('@keyword.operator', colors.noir_6)
  Group.new('@keyword.return', colors.noir_0)
  Group.new('@label', colors.noir_2)
  Group.new('@macro', colors.primary)
  Group.new('@method', colors.noir_1)
  Group.new('@method.call', colors.noir_1)
  Group.new('@namespace', colors.noir_2)
  Group.new('@none', colors.noir_3)
  Group.new('@number', colors.primary)
  Group.new('@operator', colors.noir_6)
  Group.new('@parameter', colors.noir_2)
  Group.new('@preproc', colors.noir_2)
  Group.new('@property', colors.noir_2)
  Group.new('@punctuation', colors.noir_2)
  Group.new('@punctuation.bracket', colors.noir_6)
  Group.new('@punctuation.delimiter', colors.noir_6)
  Group.new('@punctuation.special', colors.primary)
  Group.new('@repeat', colors.noir_2)
  Group.new('@storageclass', colors.noir_2)
  Group.new('@string', colors.primary)
  Group.new('@string.escape', colors.noir_2)
  Group.new('@string.special', colors.noir_2)
  Group.new('@structure', colors.noir_2)
  Group.new('@tag', colors.noir_6)
  Group.new('@tag.attribute', colors.noir_4)
  Group.new('@tag.delimiter', colors.noir_3)
  Group.new('@text.literal', colors.secondary)
  Group.new('@text.reference', colors.secondary)
  Group.new('@text.title', colors.noir_2)
  Group.new('@text.todo', colors.noir_2)
  Group.new('@text.underline', colors.noir_2)
  Group.new('@text.uri', colors.noir_2)
  Group.new('@type', colors.noir_2)
  Group.new("@identifier", colors.noir_0)
  Group.new('@type.builtin', colors.noir_6)
  Group.new('@type.definition', colors.noir_2)
  Group.new('@variable', colors.secondary)
  Group.new('@variable.builtin', colors.noir_2)
  Group.new('@lsp.type.function', colors.noir_0)
  Group.new('@lsp.type.macro', colors.primary)
  Group.new('@lsp.type.method', colors.noir_2)



  -- Semantic Highlighting
  Group.new('DiagnosticError', colors.diagnostic_error)
  Group.new('DiagnosticWarn', colors.diagnostic_warning)
  Group.new('DiagnosticInfo', colors.diagnostic_info)
  Group.new('DiagnosticHint', colors.diagnostic_hint)
  Group.new('DiagnosticSignError', colors.diagnostic_error)
  Group.new('DiagnosticSignWarn', colors.diagnostic_warning)
  Group.new('DiagnosticSignInfo', colors.diagnostic_info)
  Group.new('DiagnosticSignHint', colors.diagnostic_hint)

  Group.new("DiffAdd", nil, colors.add)
Group.new("DiffDelete", nil, colors.remove)
Group.new("DiffChange", nil, colors.change)
Group.new("DiffText", nil, colors.change)

-- LSP
Group.new("Identifier", colors.noir_0)
Group.new("@keyword.return", colors.mfed_cyan)
Group.new("@include", colors.mfed_cyan)
Group.new("@punctuation.delimiter", colors.mfed_dim)
Group.new("@tag", colors.white)
Group.new("@type.builtin", colors.mfed_dim)
Group.new("@boolean", colors.mfed_bool)
Group.new("@number", colors.mfed_num)
Group.new("@function.macro", colors.mfed_cyan)
Group.new("@macro", colors.mfed_cyan)
Group.new("@constant.macro", colors.mfed_cyan)
Group.new("@conditional", colors.mfed_cyan)
Group.new("@lsp.type.macro", colors.mfed_cyan)

-- Editor stuff
Group.new("CursorLineNr", colors.mfed_dim, nil)
Group.new("TabLine", colors.dimmed_white, nil)
Group.new("TabLineFill", nil, nil)
Group.new("VertSplit", colors.mfed_dim, nil)
Group.new("EndOfBuffer", colors.background, nil)
Group.new("ErrorMsg", colors.dimmed_red)
Group.new("Pmenu", colors.noir_2, colors.mfed_bg_accent)
Group.new("PmenuSel", colors.white, colors.change)
Group.new("StatusLine", colors.mfed_bg_accent, colors.mfed_bg_accent)

-- code action
Group.new('ActionPreviewTitle', colors.primary)
Group.new('CodeActionText', colors.secondary)
Group.new('CodeActionConceal', colors.add)

-- finder
Group.new('FinderSelection', colors.primary)
Group.new('FinderFileName', colors.noir_5)
Group.new('FinderIcon', colors.secondary)
Group.new('FinderType', colors.secondary)
Group.new('FinderCount', colors.secondary, colors.nb_background)

-- finder spinner
Group.new('FinderSpinnerTitle', colors.primary)
Group.new('FinderSpinner', colors.primary)
Group.new('FinderVirtText', colors.noir_7)
-- hover
Group.new('HoverNormal', colors.primary, colors.nb_background)
-- rename
Group.new('RenameNormal', colors.primary, colors.nb_background)
-- diagnostic
Group.new('DiagnosticSource', colors.primary)
Group.new('DiagnosticPos', colors.noir_7)
Group.new('DiagnosticWord', colors.secondary)
-- call heirarchy
Group.new('CallHierarchyIcon', colors.primary)
Group.new('CallHierarchyTitle', colors.secondary)
-- outline
Group.new('OutlineIndent', colors.noir_7)
-- terminal
Group.new('TerminalNormal', colors.secondary, colors.nb_background)

-- Signs
Group.new("diffAdded", colors.add_fg)
Group.new("diffRemoved", colors.remove_fg)
Group.new("diffChanged", colors.primary)
Group.new("diffFile", colors.primary)
Group.new("diffNewFile", colors.primary)
Group.new("diffLine", colors.primary)

-- DiffView
Group.new("DiffAdd", nil, colors.add)
Group.new("DiffDelete", nil, colors.remove)
Group.new("DiffChange", nil, colors.change)
Group.new("DiffText", nil, colors.change)

Group.new("BufferInactive", nil, colors.mfed_bg_accent)

Group.new("DiagnosticError", colors.diagnostic_error, nil)
Group.new("DiagnosticWarn", colors.yellow_fg, nil)

-- LuaLine
Group.new("LuaLineDiffChange", colors.yellow_fg, nil)
Group.new("LuaLineDiffAdd", colors.add_fg, nil)
Group.new("LuaLineDiffDelete", colors.remove_fg, nil)

-- Telescope
Group.new('TelescopeTitle', colors.noir_2)
Group.new('TelescopeBorder', colors.noir_7)
Group.new('TelescopeMatching', colors.noir_0)
Group.new('TelescopePromptCounter', colors.noir_8, nil)
Group.new("TelescopeResultsNormal", colors.mfed_dim)

-- Saga
Group.new('TitleString', colors.secondary)
Group.new('TitleSymbol', colors.primary)
Group.new('TitleIcon', colors.primary)
Group.new('SagaBorder', colors.noir_7)
Group.new('SagaNormal', nil, colors.nb_background)
Group.new('SagaExpand', colors.remove_fg)
Group.new('SagaCollapse', colors.remove_fg)
Group.new('SagaBeacon', colors.primary)

-- Obsidian
Group.new("ObsidianRefText", colors.mfed_cyan)
Group.new("ObsidianHighlightText", colors.debug)
Group.new("ObsidianTag", colors.primary)
Group.new("ObsidianExtLinkIcon", colors.mfed_navy)

-- CMP
Group.new("CmpItemAbbrDeprecated", colors.mfed_dim, nil)
Group.new("CmpItemAbbrMatch", colors.mfed_cyan)
Group.new("CmpItemAbbrMatchFuzzy", colors.mfed_cyan)

Group.new("CmpItemKindVariable", colors.mfed_navy)
Group.new("CmpItemKindInterface", colors.mfed_navy)
Group.new("CmpItemKindText", colors.mfed_navy)

Group.new("CmpItemKindFunction", colors.mfed_bool)
Group.new("CmpItemKindMethod", colors.mfed_bool)

Group.new("CmpItemKindKeyword", colors.mfed_cyan)
Group.new("CmpItemKindProperty", colors.mfed_cyan)
Group.new("CmpItemKindUnit", colors.mfed_cyan)

-- Mason
Group.new('MasonHeader', colors.secondary, colors.noir_9)
Group.new('MasonHeaderSecondary', colors.secondary)
Group.new('MasonHighlight', colors.primary)
Group.new('MasonHighlightBlock', colors.primary)
Group.new('MasonHighlightBlockBold', colors.secondary, colors.noir_9)
Group.new('MasonHighlightSecondary', colors.primary)
Group.new('MasonHighlightBlockSecondary', colors.primary)
Group.new('MasonHighlightBlockBoldSecondary', colors.secondary, colors.noir_9)
Group.new('MasonMuted', colors.noir_5)
Group.new('MasonMutedBlock', colors.noir_5)
Group.new('MasonMutedBlockBold', colors.noir_5)
Group.new('MasonError', colors.remove_fg)

-- Nvim tree
Group.new('NvimTreeRootFolder', colors.noir_6)
Group.new('NvimTreeFolderIcon', colors.primary)
Group.new("NvimTreeIndentMarker", colors.noir_6)
Group.new("NvimTreeExecFile", colors.noir_6)
Group.new("NvimTreeSpecialFile", colors.noir_2, nil)
